In [1]:
A = matrix(QQ, [[1, 0, -3, -7, 3, 1, 0, 0, 0], [0, 1, -3, -10, 1, 0, 1, 0, 0], [0, 1, -2, -7, 0, 0, 0, 1, 0], [1, 3, -12, -36, 6, 0, 0, 0, 1]])
b = vector(QQ, [0, -1/3, -1, 1])
c = vector(QQ, [-1/3, -3, -1/4, 0, 1])

In [2]:
A, b, c

(
[  1   0  -3  -7   3   1   0   0   0]                  
[  0   1  -3 -10   1   0   1   0   0]                  
[  0   1  -2  -7   0   0   0   1   0]                  
[  1   3 -12 -36   6   0   0   0   1], (0, -1/3, -1, 1),

(-1/3, -3, -1/4, 0, 1)
)

In [3]:
import itertools
import numpy as np

In [4]:
for x in itertools.combinations(range(1,10), 4):
    AB = A.matrix_from_columns([a-1 for a in x])
    if AB.det() != 0:
        rozw = AB**(-1) * b
        if (np.matrix(rozw) >= 0).all():
            print(f"Zbiór bazowy: {x}, rozwiązanie {AB**(-1) * b}")
        

Zbiór bazowy: (1, 3, 7, 9), rozwiązanie (3/2, 1/2, 7/6, 11/2)
Zbiór bazowy: (1, 4, 7, 9), rozwiązanie (1, 1/7, 23/21, 36/7)
Zbiór bazowy: (3, 5, 7, 9), rozwiązanie (1/2, 1/2, 2/3, 4)
Zbiór bazowy: (3, 6, 7, 9), rozwiązanie (1/2, 3/2, 7/6, 7)
Zbiór bazowy: (4, 5, 7, 9), rozwiązanie (1/7, 1/3, 16/21, 29/7)
Zbiór bazowy: (4, 6, 7, 9), rozwiązanie (1/7, 1, 23/21, 43/7)


In [15]:
%display typeset

A[:, 0:5]

[  1   0  -3  -7   3]
[  0   1  -3 -10   1]
[  0   1  -2  -7   0]
[  1   3 -12 -36   6]

In [16]:
P = InteractiveLPProblemStandardForm(A[:, 0:5], b, c)
P

LP problem (use 'view(...)' or '%display typeset' for details)

In [31]:
D = P.dictionary(1,3,7,9)
D

LP problem dictionary (use 'view(...)' or '%display typeset' for details)

In [32]:
D.enter("x4")
D

LP problem dictionary (use 'view(...)' or '%display typeset' for details)

In [33]:
D.leave("x3")
D

LP problem dictionary (use 'view(...)' or '%display typeset' for details)

In [34]:
D.update()
D

LP problem dictionary (use 'view(...)' or '%display typeset' for details)

In [ ]:
# co dalej?

In [36]:
# a co tutaj?

D = P.dictionary(3,5,7,9)
D

LP problem dictionary (use 'view(...)' or '%display typeset' for details)